[functions]
  directory = "netlify/functions"

[build]
  command = "pnpm -w build"
  publish = "apps/web/dist"
  functions = "apps/functions/dist"

[dev]
  command = "pnpm -w dev"
  targetPort = 5173

